const  stationData = [
  { index: 1, code: "ST", name: "Surat", district: "Surat" },
  { index: 2, code: "ADI", name: "Ahmedabad Junction", district: "Ahmedabad" },
  { index: 3, code: "BRC", name: "Vadodara Junction", district: "Vadodara" },
  { index: 4, code: "NVS", name: "Navsari", district: "Navsari" },
  { index: 5, code: "RJT", name: "Rajkot Junction", district: "Rajkot" },
  { index: 6, code: "ANND", name: "Anand Junction", district: "Anand" },
  { index: 7, code: "VAPI", name: "Vapi", district: "Vapi" },
  { index: 8, code: "ND", name: "Nadiad Junction", district: "Nadiad" },
  { index: 9, code: "BH", name: "Bharuch Junction", district: "Bharuch" },
  { index: 10, code: "BL", name: "Valsad", district: "Valsad" },
  { index: 11, code: "PNU", name: "Palanpur Junction", district: "Palanpur" },
  {
    index: 12,
    code: "AKV",
    name: "Ankleshwar Junction",
    district: "Ankleshwar",
  },
  { index: 13, code: "JAM", name: "Jamnagar", district: "Jamnagar" },
  { index: 14, code: "UDN", name: "Udhna Junction", district: "Udhna" },
  { index: 15, code: "BIM", name: "Bilimora Junction", district: "Bilimora" },
  {
    index: 16,
    code: "GIMB",
    name: "Gandhidham Junction",
    district: "Gandhidham BG",
  },
  { index: 17, code: "BHUJ", name: "Bhuj", district: "Bhuj" },
  { index: 18, code: "VG", name: "Viramgam Junction", district: "Viramgam" },
  { index: 19, code: "MSH", name: "Mehsana Junction", district: "Mehsana" },
  { index: 20, code: "DHD", name: "Dahod", district: "Dahod" },
  {
    index: 21,
    code: "SUNR",
    name: "Surendranagar Junction",
    district: "Surendranagar",
  },
  {
    index: 22,
    code: "SIOB",
    name: "Samakhiali Junction",
    district: "Samakhiali B G",
  },
  { index: 23, code: "MAN", name: "Maninagar", district: "Maninagar" },
  {
    index: 24,
    code: "MHD",
    name: "Mahemdavad Kheda Road",
    district: "Mahemdavad",
  },
  { index: 25, code: "BTD", name: "Botad Junction", district: "Botad" },
  { index: 26, code: "DWK", name: "Dwarka", district: "Dwarka" },
  { index: 27, code: "KSB", name: "Kosamba Junction", district: "Kosamba" },
  {
    index: 28,
    code: "MYG",
    name: "Miyagam Karjan Junction",
    district: "Miyagam Karjan",
  },
  { index: 29, code: "JND", name: "Junagadh Junction", district: "Junagadh" },
  { index: 30, code: "KIM", name: "Kim", district: "Kim" },
  { index: 31, code: "VRL", name: "Veraval Junction", district: "Veraval" },
  { index: 32, code: "UVD", name: "Udvada", district: "Udvada" },
  { index: 33, code: "UBR", name: "Umargam Road", district: "Umbargam Road" },
  { index: 34, code: "BVC", name: "Bhavnagar Terminus", district: "Bhavnagar" },
  { index: 35, code: "PBR", name: "Porbandar", district: "Porbandar" },
  { index: 36, code: "GDA", name: "Godhra Junction", district: "Godhra" },
  { index: 37, code: "WKR", name: "Wankaner Junction", district: "Wankaner" },
  { index: 38, code: "HAPA", name: "Hapa", district: "Hapa" },
  { index: 39, code: "SBIB", name: "Sabarmati Bg", district: "Sabarmati Bg" },
  { index: 40, code: "BCOB", name: "Bhachau", district: "Bhachau BG" },
];

// Example usage:
console.log(stationData[0]); // Output: { index: 1, code: 'ST', name: 'Surat', district: 'Surat' }
export default stationData;
